import Config

# The cache_static_manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :budgeteer, BudgeteerWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :budgeteer, BudgeteerWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # Fly's internal HTTP health check (fly.toml, checks "/") hits the app
      # directly on the internal port, bypassing Fly's edge — so it never
      # gets an x-forwarded-proto header and looks like plain HTTP here,
      # which force_ssl would otherwise 301-redirect, failing the check.
      # Safe to exclude: Fly's edge (force_https in fly.toml) already
      # redirects all real internet traffic to HTTPS before it reaches this
      # app at all.
       paths: ["/", "/health/live", "/health/ready"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
