defmodule BudgeteerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :budgeteer

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_budgeteer_key",
    signing_salt: "eE4QKri/",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :budgeteer,
    gzip: not code_reloading?,
    only: ~w(assets fonts images),
    # Plug.Static's `:only` matches the request's first path segment
    # literally, which works for directories (a nested file's digested name
    # doesn't change its first segment) but not for standalone top-level
    # files — a digested "manifest-<hash>.json" never literally equals
    # "manifest.json". `:only_matching` prefix-matches instead, which is
    # exactly what Plug.Static's own docs recommend for "digested files at
    # the root". Without this, ~p"/manifest.json" 404s in prod (verified
    # against a real deploy) since it resolves to the digested filename.
    only_matching: ~w(favicon robots manifest sw),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :budgeteer
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    # Defaults are 8MB / 15s; statement uploads allow up to 15MB and the
    # default 15s-per-socket-read timeout is too tight for a slow client
    # (e.g. reading a file from a cloud-synced folder) — see StatementController.
    length: 20_000_000,
    read_timeout: 120_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Enriches any Sentry event with request context (path, params, headers).
  # No Sentry.PlugCapture alongside it — that plug only exists to rescue
  # exceptions Cowboy would otherwise swallow; this app uses Bandit, which
  # doesn't need it (see the LoggerHandler config in application.ex).
  plug Sentry.PlugContext
  plug BudgeteerWeb.Router
end
